# Generated by Django 5.1.2 on 2024-10-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('consulta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField()),
            ],
            options={
                'db_table': 'consultas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('clave_4digitos', models.CharField(max_length=4)),
                ('clave_6digitos', models.CharField(max_length=6)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'cuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('deposito_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_depo', models.DateField()),
                ('cantidad_depo', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'depositos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retiros',
            fields=[
                ('retiro_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_retiro', models.DateField()),
                ('cantidad_retiro', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'retiros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('tarjeta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=4)),
                ('tipo_tarjeta', models.CharField(max_length=7)),
                ('fecha_caducidad', models.DateField()),
                ('fecha_emision', models.DateField()),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('transferencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_transf', models.DateField()),
                ('cantidad_transf', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'transferencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
